name: jsonpadding
description: A Jsonp library for dart
version: 1.0.2
author: Adao Junior
homepage: https://github.com/adaojunior/jsonp

environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.3.0
