name: jsonpadding
description: A Jsonp library for dart
version: 1.0.1
author: Adao Junior
homepage: https://github.com/adaojunior/jsonp
environment:
  sdk: '>=2.0.0-dev.49.0 <2.0.0'
dev_dependencies:
  test: ^0.12.30
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
