name: jsonpadding
description: A Jsonp library for dart
version: 0.1.0
author: Adao Junior <itsjunnior@gmail.com>
homepage: https://github.com/adaojunior/jsonp
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
